language: java
jdk:
- oraclejdk8
before_install:
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
- sudo apt-get update
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
  | jq -r .assets[0].browser_download_url)
after_success:
- java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter
  -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
deploy:
  provider: releases
  api_key:
    secure: bBEuV/jbKrVTcluZbkM33LRbfTn0pKUl5XyguUuFJClxUiY7mO69eXibJ8vTe69RNLwMZsTagp2+eavpvFdYyVmHaIzItAuDe1au9AfFH1j8+MjIhLSC36bInF2L6VNbC6lf1nMjAGhifr0YfntOyAMoZn6jEcZuNWXx4FnDeycPvKUv2d1BOXB3dbOfM43DD1+nZrGB5i4qnw0ovGz0glxp5LBAh3irBW/8H3yJ5olalLIn9RLYh3YK1vfBv5P+HaTU88Apw/C4AGefjxvrflEkkLSC5w8KbQcLh4Bvq3Du4LsvRkYLiIz5JIAX6oJxMOsCeQfbclq+gOfacjFr/XdegbatFTILNIm23l+YSvf1cLb1upZBERxj3CjQKw2HSiM+0cJcQz320BnxG9luXCbFHaQrZJL3+DzhdmgXOWL/5u8LQH6U1nU+VNoVNrSh1AKr3t6xuZXiHD1f/BB4psdIOJOSgMoYUjiXRNfvNhm+OMZZEg2tbF38UeXwSxFGHr/bhVQ4QsWl2Rro6c76uX1XuWsqljbgwIkiulW1HmmDWpIaQzH66wDYVj1KvdzjZEkFAIvINSA5loGsfUcdMZZZ+pYBbnNu+PW6+3LtKus6G/9pEOrRfXBWO53Ax8GqKqXnokqv0LFR3gi/rPyIB6CAEE4UyMBgVBb0qjY+ucY=
  file: target/jsonconfig.jar
  skip_cleanup: true
  on:
    repo: binaryoverload/JSON-Config
    tags: true
    all_branches: true
